export default defineAppConfig({
  ui: {
    colors: {
      primary: "dusty-olive",
      secondary: "old-gold",
      tertiary: "vintage-lavender",
      neutral: "grey-olive",
    },
    icons: {
      arrowDown: "far:arrow-down",
      arrowLeft: "far:arrow-left",
      arrowRight: "far:arrow-right",
      arrowUp: "far:arrow-up",
      caution: "far:circle-alert",
      check: "far:check",
      chevronDoubleLeft: "far:chevrons-left",
      chevronDoubleRight: "far:chevrons-right",
      chevronDown: "far:chevron-down",
      chevronLeft: "far:chevron-left",
      chevronRight: "far:chevron-right",
      chevronUp: "far:chevron-up",
      close: "far:x",
      copy: "far:copy",
      copyCheck: "far:copy-check",
      dark: "far:moon",
      drag: "far:grip-vertical",
      ellipsis: "far:ellipsis",
      error: "far:circle-x",
      external: "far:arrow-up-right",
      eye: "far:eye",
      eyeOff: "far:eye-off",
      file: "far:file",
      folder: "far:folder",
      folderOpen: "far:folder-open",
      hash: "far:hash",
      info: "far:info",
      light: "far:sun-bright",
      loading: "far:loader-circle",
      mail: "far:envelope",
      menu: "far:bars",
      minus: "far:minus",
      panelClose: "far:panel-left-close",
      panelOpen: "far:panel-left-open",
      plus: "far:plus",
      reload: "far:rotate-ccw",
      search: "far:search",
      stop: "far:square",
      success: "far:circle-check",
      system: "far:monitor",
      tip: "far:lightbulb",
      upload: "far:upload",
      warning: "far:triangle-alert",
    },
  },
});
